from uuid import UUID
from pydantic import BaseModel, field_serializer
from datetime import datetime

# Base Schema (Shared properties) - in java, parent class 
class IngredientBase(BaseModel):
    name : str

# What Frontend sends
# only need name since id and created_dt are auto-generated by database
class IngredientCreate(IngredientBase):
    pass

class IngredientUpdate(IngredientBase):
    name : str
    # Optional[str] = None

# sending data back to Frontend
# includes all properties
class IngredientResponse(IngredientBase):
    id: int
    user_id: UUID
    create_dt: datetime
    update_dt: datetime | None

    class Config:
        from_attributes = True