from uuid import UUID
from pydantic import BaseModel, field_serializer
from datetime import datetime

# Base Schema (Shared properties) - in java, parent class 
class MealIngredientBase(BaseModel):
    meal_id: int
    ingredient_id: int
    quantity: str

# What Frontend sends
# only need name since id and created_dt are auto-generated by database
class MealIngredientCreate(MealIngredientBase):
    pass

# sending data back to Frontend
# includes all properties
class MealIngredientResponse(MealIngredientBase):
    id: int
    create_dt: datetime
    
    class Config:
        from_attributes = True