from pydantic import BaseModel
from datetime import datetime

# Base Schema (Shared properties) - in java, parent class 
class MealBase(BaseModel):
    name : str

# What Frontend sends
# only need name since id and created_dt are auto-generated by database
class MealCreate(MealBase):
    pass

# sending data back to Frontend
# includes all properties
class MealResponse(MealBase):
    id: int
    user_id: str
    created_dt: datetime

    class Config:
        from_attributes = True