from uuid import UUID
from pydantic import BaseModel, field_serializer, EmailStr
from datetime import datetime

# Base Schema (Shared properties) - in java, parent class 
class UserBase(BaseModel):
    nickname : str
    is_active : bool = True

# What Frontend sends
# only need name since id and created_dt are auto-generated by database
class UserCreate(UserBase):
    email : EmailStr
    password: str

# Password changes -> separate, secure endpoint
class UserUpdate(UserBase):
    nickname : str
    is_active : bool | None = None
    
# sending data back to Frontend
# includes all properties
class UserResponse(UserBase):
    id: UUID
    create_dt: datetime
    update_dt: datetime | None

    class Config:
        from_attributes = True